apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd          # Vẫn bắt buộc là argocd để App Root quản lý
spec:
  source:
    repoURL: https://argoproj.github.io/argo-helm   # Đường dẫn kho của Argo
    chart: argo-rollouts                            # Tên chart của Rollouts
    targetRevision: 2.37.7                          # Phiên bản chuẩn của Rollouts
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts # Nơi chứa bộ điều khiển Canary Rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true